name: firestore_https_flutter
description: Firestore MCP server over streaming HTTP transport deployed to Cloud Run
version: 1.0.22
repository: https://github.com/xbill9/gemini-cli-codeassist

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  mcp_dart: ^1.2.0
  args: ^2.5.0
  firedart: ^0.9.8
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
